name: Publish Development Package

on:
  push:
    branches:
      - 'dev/**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Generate version tag from branch name
        run: |
          # Extract branch name, remove the "dev/" prefix
          RAW_BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          CLEAN_BRANCH_NAME="${RAW_BRANCH_NAME#dev/}"
          BRANCH_SUFFIX="dev-${CLEAN_BRANCH_NAME}"
          echo "Branch name for tag: $BRANCH_SUFFIX"
          # Create a tag for the branch
          git tag "$BRANCH_SUFFIX"
          git push origin "$BRANCH_SUFFIX"

      - name: Publish to GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          npm publish --registry=https://npm.pkg.github.com/
