name: Publish Development Package

on:
  push:
    branches:
      - 'dev/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          scope: '@exelarium'
      - run: npm ci
      - name: Publish to GitHub
        run: npm publish --registry https://npm.pkg.github.com --access private
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
